# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael's Weird Blog
email: themichaeleden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Author Michael Eden (engineer) experiments with the idea of having a creative outlet.
  Watch him fall back on his crutch by writing about cool tech and read his strange
  writing, the only guarantee is that the content is wholly his own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://icanteden.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: illegalprime
signature: — Michael

paginate: 5
permalink: pretty

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
